# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "./GtfsFeedValidator/GtfsFeedValidator.sln"
    - name: Build
      run: dotnet build "./GtfsFeedValidator/GtfsFeedValidator.sln" -c Release --no-restore
    - name: Test
      run: |
        wget https://github.com/MobilityData/gtfs-validator/releases/download/v5.0.1/gtfs-validator-5.0.1-cli.jar -O ./GtfsFeedValidator.Test/bin/Release/net8.0/gtfs-validator-5.0.1-cli.jar
        dotnet test "./GtfsFeedValidator.Test/bin/Release/net8.0/GtfsFeedValidator.Test.dll" --no-build --verbosity normal
